package:
  name: paraeigen
  version: 0.0.1

build:
  number: 3

source:
  path: ../..

requirements:
  build:
    - python
    - cmake
    - pybind11          #   - pybind
    - eigen             #   - looooo
  run:
    - python

about:
  summary: some eigen-wrappers
