package:
  name: paraeigen
  version: 0.0.1

build:
  number: 1

source:
  path: ../

requirements:
  build:
    - cmake
    - pybind11          #   - https://conda.anaconda.org/pybind
    - eigen             #   - https://conda.anaconda.org/rmg
  run:
    - python

about:
  summary: some eigen-wrappers
